/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import conexiondb.postgreeConexion;
import datos.datosPaciente;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

public class controlPacientes extends javax.swing.JFrame {

    List<datosPaciente> listaPacientes; //lista para los pacientes
    datosPaciente datosPaciente;
    public controlPacientes() {
        initComponents();
        listaPacientes = new ArrayList<>(); //se crea la lista
        datosPaciente = new datosPaciente(); //se crea una instancia
        actualizarTabla();
    }

    private void actualizarTabla(){
        listaPacientes.clear();
        //se crea una nueva conexion a la base de datos
        postgreeConexion conexion = new postgreeConexion();
        Connection CONEXION = conexion.connectarPostgree();
        try{ //aqui debe ir el codigo para consultas a la base de datos
            //Se prepara la consulta SQL
            String SQL = "SELECT cui, nombre, sex, tel, dic, depa, muni, edad FROM public.paciente";
            
            Statement statement = CONEXION.createStatement(); //creamos variable para ejecutar instrucciones sql
            ResultSet rs = statement.executeQuery(SQL);//ejecutamos la consulta y la guardamos en rs
            while(rs.next()){ //recorremos rs fila por fila
                datosPaciente datos = new datosPaciente();
                //agrego los datos de la db a los atributos de la clase paciente
                datos.setCui(rs.getLong("cui"));
                datos.setNombre(rs.getString("nombre"));
                datos.setSexo(rs.getString("sex"));
                datos.setTel(rs.getLong("tel")); 
                datos.setDic(rs.getString("dic"));
                datos.setDepa(rs.getString("depa"));
                datos.setMuni(rs.getString("muni"));
                datos.setFecha(rs.getDate("edad").toString());
                listaPacientes.add(datos); 
            }
            CONEXION.close();
            CONEXION = null;
            conexion = null;
        } catch(SQLException ex){
        }
        //Se crea una Matriz del Tamanio de la Lista
        int filas = 4;
        if(listaPacientes.size() > 4){
            filas = listaPacientes.size();
        }
        String[][] matriz = new String[filas][8];
        for(int i = 0; i < listaPacientes.size(); i++){
          matriz[i][0] = String.valueOf(listaPacientes.get(i).getCui());
          matriz[i][1] = listaPacientes.get(i).getNombre();
          matriz[i][2] = listaPacientes.get(i).getSexo();
          matriz[i][3] = String.valueOf(listaPacientes.get(i).getTel());
          matriz[i][4] = listaPacientes.get(i).getDic();
          matriz[i][5] = listaPacientes.get(i).getDepa();
          matriz[i][6] = listaPacientes.get(i).getMuni();
          matriz[i][7] = listaPacientes.get(i).getFecha();
          
        }
        // Se setea mi tabla para mostrar en pantalla
        Pacientes.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "CUI", "NOMBRE", "SEXO", "TELEFONO", "DIRECCION", "DEPARTAMENTO", "MUNICIPIO", "FECHA NACIEMIENTO"
                }
        ));
        //Centramos la Data del JTable
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int x = 0; x < 8; x++){
            Pacientes.getColumnModel().getColumn(x).setCellRenderer(centerRenderer);
        }
    }
    
    private void Mensaje(String pMensaje){
        JOptionPane.showMessageDialog(null, pMensaje);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rcui = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rnombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rtel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rdic = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rsexo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        rdepa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rmuni = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        fechaNacimiento = new com.toedter.calendar.JCalendar();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        acui = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        atel = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        asex = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        adepa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        amuni = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        adic = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        anombre = new javax.swing.JTextField();
        abuscar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        aEdad = new com.toedter.calendar.JCalendar();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ecui = new javax.swing.JTextField();
        ebuscar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        labelEdad = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelDic = new javax.swing.JLabel();
        esex = new javax.swing.JLabel();
        edepa = new javax.swing.JLabel();
        etel = new javax.swing.JLabel();
        emuni = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pacientes = new javax.swing.JTable();
        busquedaPaciente = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("REGISTRO DE NUEVO PACIENTE");

        jLabel4.setText("CUI:");

        jLabel5.setText("NOMBRE COMPLETO:");

        rnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnombreActionPerformed(evt);
            }
        });

        jLabel6.setText("TEL:");

        rtel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtelActionPerformed(evt);
            }
        });

        jLabel7.setText("DIRECCION RESIDENCIA:");

        jLabel8.setText("FECHA DE NACIMIENTO:");

        jLabel9.setText("SEXO:");

        rsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECCIONE-", "MASCULINO", "FEMENINO" }));

        jLabel10.setText("DEPARTAMENTO:");

        jLabel11.setText("MUNICIPIO:");

        registrar.setText("REGISTRAR PACIENTE");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(353, 353, 353))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdepa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rmuni))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rsexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rtel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rcui, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rnombre)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdic, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(rcui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(rtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(rnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(rdic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(rsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(rdepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(rmuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)
                            .addComponent(fechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jTabbedPane6.addTab("REGISTRO", jPanel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ACTUALIZAR DATOS PACIENTE");

        jLabel12.setText("CUI:");

        jLabel13.setText("TEL:");

        jLabel14.setText("SEXO:");

        asex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECCIONE-", "MASCULINO", "FEMENINO" }));

        jLabel15.setText("DEPARTAMENTO:");

        jLabel16.setText("MUNICIPIO:");

        jLabel17.setText("FECHA DE NACIMIENTO:");

        jLabel18.setText("DIRECCION RESIDENCIA:");

        jLabel19.setText("NOMBRE COMPLETO:");

        abuscar.setText("BUSCAR");
        abuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abuscarActionPerformed(evt);
            }
        });

        actualizar.setText("ACTUALIZAR DATOS DEL PACIENTE");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abuscar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(adepa))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(asex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(atel, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(amuni, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anombre))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adic, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(actualizar)
                        .addGap(327, 327, 327)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(acui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(anombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abuscar))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(atel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(adic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(asex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(adepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(amuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jTabbedPane6.addTab("ACTUALIZAR", jPanel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ELIMINAR DATOS DEL PACIENTE");

        jLabel20.setText("CUI:");

        ebuscar.setText("BUSCAR");
        ebuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebuscarActionPerformed(evt);
            }
        });

        jLabel21.setText("TEL:");

        jLabel22.setText("SEXO:");

        jLabel23.setText("DEPARTAMENTO:");

        eliminar.setText("ELIMINAR DATOS DEL PACIENTE");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel24.setText("MUNICIPIO:");

        jLabel25.setText("FECHA DE NACIMIENTO:");

        jLabel26.setText("DIRECCION RESIDENCIA:");

        jLabel27.setText("NOMBRE COMPLETO:");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labelEdad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        labelDic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        esex.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        edepa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        etel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        emuni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ecui, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ebuscar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edepa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(esex, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(407, 407, 407)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emuni, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminar)
                .addGap(336, 336, 336))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(ecui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(ebuscar)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel26))
                            .addComponent(labelDic, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel22)
                                            .addComponent(esex, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel23))
                                    .addComponent(edepa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24)
                                    .addComponent(emuni, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(labelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))
                    .addComponent(jSeparator3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jTabbedPane6.addTab("ELIMINAR", jPanel3);

        jTabbedPane1.addTab("FORMULARIO PACIENTES", jTabbedPane6);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("LISTADO DE TODOS LOS PACIENTES EN EL HOSPITAL");

        Pacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CUI", "NOMBRE", "SEXO", "TELEFONO", "DIRECCION", "DEPARTAMENTO", "MUNICIPIO", "FECHA NACIMIENTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Pacientes);

        busquedaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaPacienteActionPerformed(evt);
            }
        });
        busquedaPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busquedaPacienteKeyReleased(evt);
            }
        });

        jLabel29.setText("BUSCAR PACIENTE:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(292, 292, 292))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(busquedaPaciente)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busquedaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("LISTADO DE PACIENTES", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // ELIMINAR AL PACIENTE DE LA BASE DE DATOS
        postgreeConexion conexion = new postgreeConexion();
        Connection CONEXION = conexion.connectarPostgree();

        try{
            PreparedStatement delete;
            delete = CONEXION.prepareStatement("DELETE FROM public.paciente WHERE cui = '"+Long.parseLong(ecui.getText())+"' ");
            delete.executeUpdate();
            CONEXION.close();//Cerramos la conexion
            CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
            conexion = null;
            Mensaje("DATOS ELIMINADO CON EXITO");
        } catch (Exception e){
            Mensaje("Error al Eliminar Reporte del Paciente: " + e.getMessage());
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void ebuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebuscarActionPerformed
        // BUSCAR PARA ELIMINAR
        postgreeConexion conexion = new postgreeConexion(); //se crea una nueva conexion hacia la base de datos
        Connection CONEXION = conexion.connectarPostgree();

        try{
            String SQL = "SELECT nombre, tel, dic, sex, depa, muni, edad "
            + "FROM public.paciente WHERE cui = '"+Long.parseLong(ecui.getText())+"' ";
            Statement statement = CONEXION.createStatement();
            ResultSet rs = statement.executeQuery(SQL);

            while(rs.next()){
                labelNombre.setText(rs.getString("nombre"));
                labelDic.setText(rs.getString("dic"));
                esex.setText(rs.getString("sex"));
                edepa.setText(rs.getString("depa"));
                etel.setText( String.valueOf(rs.getLong("tel")));
                emuni.setText(rs.getString("muni"));
                labelEdad.setText(rs.getDate("edad").toString());
            }

            CONEXION.close();//Cerramos la conexion
            CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
            conexion = null;
        }catch(SQLException ex){

        }
    }//GEN-LAST:event_ebuscarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // ACTUALIZAR DATOS DEL PACIENTE
        datosPaciente = new datosPaciente();
        //Creamos una nueva conexion a la base de datos
        postgreeConexion conexion = new postgreeConexion();
        Connection CONEXION = conexion.connectarPostgree();

        try{
            //se arma la consulta a SQL
            String SQL = "UPDATE public.paciente SET nombre = ?, dic = ?, tel = ?, sex = ?, depa = ?, muni = ?, edad =? "
            + "WHERE cui = '"+Long.parseLong(acui.getText())+"' ";
            //creamos la variable para generar las consultas
            PreparedStatement statement;
            //preparamos a statement para ejecutar la consulta
            statement = CONEXION.prepareStatement(SQL);
            //agregamos los valores a la consulta
            statement.setString(1, anombre.getText());
            statement.setString(2, adic.getText());
            statement.setLong(3, Long.parseLong(atel.getText()));
            statement.setString(4, asex.getSelectedItem().toString());
            statement.setString(5, adepa.getText());
            statement.setString(6, amuni.getText());
            statement.setDate(7, new java.sql.Date(aEdad.getDate().getTime()));
            int filasInsertadas = statement.executeUpdate();//Se ejecuta la consulta
            System.out.println("Insertado:" + filasInsertadas);//Se muestran las filas insertadas

            CONEXION.close();//Cerramos la conexion
            CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
            conexion = null;
            Mensaje("DATOS ACTUALIZADOS CON EXITO");
            actualizarTabla();
        } catch(SQLException ex){
            Mensaje("ERROR AL ACTUALIZAR DATOS: " + ex.getMessage());
        }

    }//GEN-LAST:event_actualizarActionPerformed

    private void abuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abuscarActionPerformed
        // BUSCAR AL PACIENTE POR MEDIO DE SU CUI
        postgreeConexion conexion = new postgreeConexion(); //se crea una nueva conexion hacia la base de datos
        Connection CONEXION = conexion.connectarPostgree();

        try{
            String SQL = "SELECT nombre, tel, dic, sex, depa, muni, edad "
            + "FROM public.paciente WHERE cui = '"+Long.parseLong(acui.getText())+"' ";
            Statement statement = CONEXION.createStatement();
            ResultSet rs = statement.executeQuery(SQL);

            while(rs.next()){
                anombre.setText(rs.getString("nombre"));
                adic.setText(rs.getString("dic"));
                asex.setSelectedItem(rs.getString("sex"));
                adepa.setText(rs.getString("depa"));
                atel.setText(rs.getString("tel"));
                amuni.setText(rs.getString("muni"));
                aEdad.setDate(rs.getDate("edad"));
            }

            CONEXION.close();//Cerramos la conexion
            CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
            conexion = null;
        }catch(SQLException ex){

        }
    }//GEN-LAST:event_abuscarActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // CODIGO PARA REGISTRAR EL PACIENTE A LA BASE DE DATOS
        datosPaciente = new datosPaciente();
        System.out.println("SE COMIENZA EL PROCESO PARA REGISTRAR UN NUEVO PACIENTE");
        datosPaciente.setCui(Long.parseLong(rcui.getText()));
        datosPaciente.setNombre(rnombre.getText());
        datosPaciente.setTel(Long.parseLong(rtel.getText()));
        datosPaciente.setSexo(rsexo.getSelectedItem().toString());
        datosPaciente.setDepa(rdepa.getText());
        datosPaciente.setMuni(rmuni.getText());
        datosPaciente.setDic(rdic.getText());
        datosPaciente.setFecha(fechaNacimiento.getDate().toString());

        postgreeConexion conexion = new postgreeConexion(); //se crea una nueva conexion hacia la base de datos
        Connection CONEXION = conexion.connectarPostgree();

        try{
            String SQL = "INSERT INTO public.paciente"
            + "(cui, nombre, dic, sex, tel, depa, muni, edad)"
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement statement = CONEXION.prepareStatement(SQL);
            statement.setLong(1, datosPaciente.getCui()); //agregamos los valores a la consulta
            statement.setString(2, datosPaciente.getNombre());
            statement.setString(3, datosPaciente.getDic());
            statement.setString(4, datosPaciente.getSexo());
            statement.setLong(5, datosPaciente.getTel());
            statement.setString(6, datosPaciente.getDepa());
            statement.setString(7, datosPaciente.getMuni());
            SimpleDateFormat sdf = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy", Locale.ENGLISH);
            Date fechaNacimientoDate = new Date(sdf.parse(datosPaciente.getFecha()).getTime());
            statement.setDate(8, fechaNacimientoDate); // se pasa el objeto Date
            int filasInsertadas = statement.executeUpdate();//Se ejecuta la consulta
            System.out.println("Insertado:" + filasInsertadas);//Se muestran las filas insertadas
            CONEXION.close();//Cerramos la conexion
            CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
            conexion = null;
            Mensaje("PACIENTE REGISTRADO");
            actualizarTabla();
        } catch(SQLException ex){
            Mensaje("Error al grabar datos del Paciente: " + ex.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(controlPacientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void rtelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtelActionPerformed

    private void rnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnombreActionPerformed

    private void busquedaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaPacienteActionPerformed

    private void busquedaPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaPacienteKeyReleased
        // BUSQUEDA A TIEMPO REAL DEL PACIENTE
        buscarPaciente(busquedaPaciente.getText());
    }//GEN-LAST:event_busquedaPacienteKeyReleased

    private void buscarPaciente(String buscar){
        listaPacientes.clear();
        //se crea una nueva conexion a la base de datos
        postgreeConexion conexion = new postgreeConexion();
        Connection CONEXION = conexion.connectarPostgree();
        try{ //aqui debe ir el codigo para consultas a la base de datos
            //Se prepara la consulta SQL
            String SQL = "SELECT cui, nombre, sex, tel, dic, depa, muni, edad FROM public.paciente WHERE (nombre ILIKE '%"+buscar+"%' OR CAST(cui AS TEXT) LIKE '%"+buscar+"%') ";
            
            Statement statement = CONEXION.createStatement(); //creamos variable para ejecutar instrucciones sql
            ResultSet rs = statement.executeQuery(SQL);//ejecutamos la consulta y la guardamos en rs
            while(rs.next()){ //recorremos rs fila por fila
                datosPaciente datos = new datosPaciente();
                //agrego los datos de la db a los atributos de la clase paciente
                datos.setCui(rs.getLong("cui"));
                datos.setNombre(rs.getString("nombre"));
                datos.setSexo(rs.getString("sex"));
                datos.setTel(rs.getLong("tel")); 
                datos.setDic(rs.getString("dic"));
                datos.setDepa(rs.getString("depa"));
                datos.setMuni(rs.getString("muni"));
                datos.setFecha(rs.getDate("edad").toString());
                listaPacientes.add(datos); 
            }
            CONEXION.close();
            CONEXION = null;
            conexion = null;
        } catch(SQLException ex){
        }
        //Se crea una Matriz del Tamanio de la Lista
        int filas = 4;
        if(listaPacientes.size() > 4){
            filas = listaPacientes.size();
        }
        String[][] matriz = new String[filas][8];
        for(int i = 0; i < listaPacientes.size(); i++){
          matriz[i][0] = String.valueOf(listaPacientes.get(i).getCui());
          matriz[i][1] = listaPacientes.get(i).getNombre();
          matriz[i][2] = listaPacientes.get(i).getSexo();
          matriz[i][3] = String.valueOf(listaPacientes.get(i).getTel());
          matriz[i][4] = listaPacientes.get(i).getDic();
          matriz[i][5] = listaPacientes.get(i).getDepa();
          matriz[i][6] = listaPacientes.get(i).getMuni();
          matriz[i][7] = listaPacientes.get(i).getFecha();
          
        }
        // Se setea mi tabla para mostrar en pantalla
        Pacientes.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "CUI", "NOMBRE", "SEXO", "TELEFONO", "DIRECCION", "DEPARTAMENTO", "MUNICIPIO", "FECHA NACIEMIENTO"
                }
        ));
        //Centramos la Data del JTable
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int x = 0; x < 8; x++){
            Pacientes.getColumnModel().getColumn(x).setCellRenderer(centerRenderer);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controlPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controlPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controlPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controlPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new controlPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Pacientes;
    private com.toedter.calendar.JCalendar aEdad;
    private javax.swing.JButton abuscar;
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField acui;
    private javax.swing.JTextField adepa;
    private javax.swing.JTextField adic;
    private javax.swing.JTextField amuni;
    private javax.swing.JTextField anombre;
    private javax.swing.JComboBox<String> asex;
    private javax.swing.JTextField atel;
    private javax.swing.JTextField busquedaPaciente;
    private javax.swing.JButton ebuscar;
    private javax.swing.JTextField ecui;
    private javax.swing.JLabel edepa;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel emuni;
    private javax.swing.JLabel esex;
    private javax.swing.JLabel etel;
    private com.toedter.calendar.JCalendar fechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JLabel labelDic;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField rcui;
    private javax.swing.JTextField rdepa;
    private javax.swing.JTextField rdic;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField rmuni;
    private javax.swing.JTextField rnombre;
    private javax.swing.JComboBox<String> rsexo;
    private javax.swing.JTextField rtel;
    // End of variables declaration//GEN-END:variables
}
