/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import conexiondb.postgreeConexion;
import extras.TextPrompt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import sun.awt.resources.awt;


public class login extends javax.swing.JFrame {
    TextPrompt placeHolder;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        placeholders();
    }

    private void placeholders(){
         placeHolder = new TextPrompt("Ingrese su usuario...", usuario);
         placeHolder = new TextPrompt("Ingrese su contraseña...", password);
         placeHolder = new TextPrompt("Ingrese nuevo usuario...", newusuario);
         placeHolder = new TextPrompt("Ingrese nueva contraseña...", newpassword);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        crearusuario = new javax.swing.JButton();
        newusuario = new javax.swing.JTextField();
        newpassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login.setText("CONFIRMAR");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INICIAR SESION");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(login)))
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(password))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(login)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("INICIO DE SESION DEL USUARIO", jPanel1);

        crearusuario.setText("CONFIRMAR");
        crearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearusuarioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CREAR UN NUEVO USUARIO");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(crearusuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(newpassword)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newusuario)))
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(104, 104, 104)
                .addComponent(newusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(newpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(crearusuario)
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("CREAR UN NUEVO USUARIO EN LA BASE DE DATOS", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void crearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearusuarioActionPerformed
        // CREAR NUEVO USUARIO
        if(newusuario.getText().equals("")){
            Mensaje("Debe de ingresar su Usuario");
        } else if(newpassword.getText().equals("")){
            Mensaje("Debe de ingresar su Password");
        } else {
            postgreeConexion conexion = new postgreeConexion(); //se crea una nueva conexion hacia la base de datos
            Connection CONEXION = conexion.connectarPostgree();
            String u = newusuario.getText();
            String p = newpassword.getText();
            try{
                String SQL = "INSERT INTO public.usuarios (usuario, clave) VALUES (?, ?)";
                PreparedStatement statement = CONEXION.prepareStatement(SQL);
                statement.setString(1, u);
                statement.setString(2, p);
                int filasInsertadas = statement.executeUpdate();//Se ejecuta la consulta
                System.out.println("Insertado:" + filasInsertadas);//Se muestran las filas insertadas
                CONEXION.close();//Cerramos la conexion
                CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
                conexion = null;
                Mensaje("USUARIO REGISTRADO");
            } catch(SQLException ex){
                //Logger.getLogger(Reportes_Agregar.class.getName()).log(Level.SEVERE, null, ex);
                Mensaje("ERROR AL CREAR NUEVO USUARIO: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_crearusuarioActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // INICIO DE SESION
        if(usuario.getText().equals("")){
            Mensaje("Debe de ingresar su Usuario");
        } else if(password.getText().equals("")){
            Mensaje("Debe de ingresar su Password");
        } else {
            postgreeConexion conexion = new postgreeConexion(); //se crea una nueva conexion hacia la base de datos
            Connection CONEXION = conexion.connectarPostgree();
            String u = usuario.getText();
            String p = password.getText();
            try{
                String SQL = "SELECT usuario, clave FROM public.usuarios "
                        + "WHERE usuario = '"+u+"' AND clave = '"+p+"' ";
                Statement statement = CONEXION.createStatement();
                ResultSet rs = statement.executeQuery(SQL);
                if(rs.next()){
                    System.out.println("ACCESO CONCEDIDO");
                    setVisible(false);
                    controlPacientes control = new controlPacientes();
                    control.setVisible(true);
                } else{
                    Mensaje("Usuario o Password Invalidos");
                }
                CONEXION.close();
                CONEXION = null;
                conexion = null;
            } catch(SQLException ex){
                //Logger.getLogger(Reportes_Agregar.class.getName()).log(Level.SEVERE, null, ex);
                Mensaje("Error Crear un Nuevo Reporte: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_loginActionPerformed

    private void Mensaje(String pMensaje){
        JOptionPane.showMessageDialog(null, pMensaje);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearusuario;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton login;
    private javax.swing.JTextField newpassword;
    private javax.swing.JTextField newusuario;
    private javax.swing.JTextField password;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
